

[build.environment]
  NODE_VERSION = "18.12.1"
  NPM_VERSION = "8.19.2"

[build]
  command = "npm run build:prod"
  publish = "/dist/async-frontend"
  base ="/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200